name: Build Kivy APK with Buildozer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-20.04  # استخدام Ubuntu 20.04 للاستقرار

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Python 3.9 أكثر استقراراً مع Buildozer

      # تثبيت Java 8 (الأكثر استقراراً مع Android SDK)
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      # تثبيت Android SDK بالطريقة الصحيحة
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30  # تقليل مستوى API لتجنب مشاكل AIDL
          build-tools: 30.0.3  # إصدار مُجرب وموثوق
          ndk-version: 23.2.8568313  # إصدار NDK متوافق

      # تثبيت متطلبات النظام
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            ccache \
            autotools-dev \
            autoconf \
            libtool \
            pkg-config

      # تثبيت Python packages بالإصدارات المحددة
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install "cython==0.29.33"
          pip install "buildozer==1.5.0"
          pip install "kivy==2.1.0"
          pip install colorama appdirs sh jinja2 six

      # إنشاء ملف خط عربي وهمي (لتجنب الأخطاء)
      - name: Create dummy Arabic font
        run: |
          # إنشاء ملف نصي بدلاً من خط حقيقي (مؤقت)
          echo "dummy font file" > arabic_font.ttf

      # تحديث buildozer.spec تلقائياً
      - name: Update buildozer.spec
        run: |
          # إنشاء buildozer.spec محدث
          cat > buildozer.spec << 'EOF'
          [app]
          title = Smart Calculator
          package.name = smartcalculator
          package.domain = com.example.smartcalc
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas,ttf,txt
          version = 1.0
          requirements = python3,kivy==2.1.0,pillow,android
          permission = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE
          orientation = portrait
          fullscreen = 0
          
          [buildozer]
          log_level = 2
          warn_on_root = 1
          
          # Android specific
          android.api = 30
          android.minapi = 21
          android.ndk = 23.2.8568313
          android.sdk = 30
          android.accept_sdk_license = True
          android.arch = armeabi-v7a,arm64-v8a
          android.gradle_dependencies = 
          android.add_java_dir = 
          android.add_compile_options = 
          android.add_gradle_repositories = 
          android.gradle_repositories = google(), mavenCentral()
          android.enable_androidx = False
          android.compile_options = 1.8, 1.8
          EOF

      # تنظيف وإعداد Buildozer
      - name: Initialize Buildozer
        run: |
          buildozer android clean
          buildozer android update --verbose

      # بناء APK
      - name: Build APK
        run: |
          buildozer android debug --verbose
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          ANDROID_NDK_ROOT: ${{ env.ANDROID_NDK_ROOT }}

      # رفع APK كـ artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SmartCalculator-APK
          path: bin/*.apk
          retention-days: 30

      # رفع logs في حالة الفشل
      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            .buildozer/
            buildozer.log
          retention-days: 7
