name: Build Kivy APK with Buildozer

on:
  push:
    branches: [ "main" ] # يعمل عند الدفع إلى الفرع الرئيسي
  workflow_dispatch: # يسمح بتشغيله يدوياً من واجهة GitHub Actions

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies and buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          pip install --upgrade "cython==0.29.33"
          pip install --upgrade "buildozer==1.5.0"
          pip install --upgrade "kivy[full]==2.2.1"

      - name: Build the APK
        run: |
          buildozer -v android debug

      - name: Upload the APK as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmartCalculator-APK
          path: bin/*.apk
