name: Build Kivy APK with Buildozer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies + Buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          pip install --upgrade "cython==0.29.33"
          pip install --upgrade "buildozer==1.5.0"
          pip install --upgrade "kivy[full]==2.2.1"

      # تثبيت Android SDK و Build-Tools أولاً
      - name: Install Android SDK & Build-Tools
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools: 33.0.2
          cmdline-tools: true

      # تثبيت platform-tools بعد تثبيت SDK
      - name: Install platform-tools
        run: |
          sdkmanager "platform-tools"

      # تصدير متغيّرات المسار للـ SDK
      - name: Export Android SDK paths
        run: |
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/build-tools/33.0.2:$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_ENV

      - name: Build the APK
        run: |
          buildozer -v android debug

      - name: Upload the APK as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmartCalculator-APK
          path: bin/*.apk
